### ISSUE TITLE
Writing Custom Types

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [flyerhq/flutter_chat_types#28]
writing custom types is a pain currently for me how can it do that can someone reference me please?

**Comment by demchenkoalex** [comment]
I did not get that. Could you elaborate?

**Comment by Yogesh-Dubey-Ayesavi** [comment]
@demchenkoalex  I wanted to write a custom  type of audio message

**Comment by demchenkoalex** [comment]
just copy some other type (I guess image will be somewhat similar) and add properties you want to have for the audio?

**Comment by Mayb3Nots** [comment]
Hi @demchenkoalex after you updated the `CustomMessage` class to use factory, Im having trouble with the implementation it was working before but now it doesnt. Is there maybe a sample code we can see on how to implement it our self?

**Comment by demchenkoalex** [comment]
Hey @Mayb3Nots you don't need to create your CustomMessage no? You just use it (metadata field). Or you asking about your message type you add in your fork? The repo itself is the example, copying one of the message types shouldn't be hard?

**Comment by Mayb3Nots** [comment]
> Hey @Mayb3Nots you don't need to create your CustomMessage no? You just use it (metadata field). Or you asking about your message type you add in your fork? The repo itself is the example, copying one of the message types shouldn't be hard?

I just realized you can use `CustomMessage ` without creating a new class. What? I thought it was an abstract class.

**Comment by Mayb3Nots** [comment]
Just FYI this was my implementation before the factory constructor, is it possible to still do this?

import 'package:equatable/equatable.dart';
import 'package:flutter_chat_types/flutter_chat_types.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:smap/models/JsonSerializable/community_activities_data.dart';
import 'package:smap/models/enums/custom_message_type.dart';

class CommunityActivityMessage extends CustomMessage with EquatableMixin {
  CommunityActivityMessage({
    required CommunityActivitiesData data,
    required super.author,
    required super.id,
    super.type = MessageType.custom,
    super.createdAt,
    Map<String, dynamic>? metadata,
    required super.roomId,
    super.status,
  }) : super(metadata: {
          ...?metadata,
          'custom_type': CustomMessageType.communityActivityMessage.name,
          ...{'activity_data': data.toJson()}
        });

  CommunityActivitiesData get data =>
      CommunityActivitiesData.fromJson(metadata?['activity_data']);

  factory CommunityActivityMessage.fromJson(Map<String, dynamic> json) =>
      _$CommunityActivityMessageFromJson(json);

  factory CommunityActivityMessage.fromFirestore(Map<String, dynamic> doc) {
    return CommunityActivityMessage.fromJson(
        {'data': doc['metadata']['activity_data'], ...doc});
  }
  // Not using jsonserializable for this one because it doesn't convert properly or idk how to configure it xd
  @override
  Map<String, dynamic> toJson() => _$CommunityActivityMessageToJson(this);
}

CommunityActivityMessage _$CommunityActivityMessageFromJson(
        Map<String, dynamic> json) =>
    CommunityActivityMessage(
      data: CommunityActivitiesData.fromJson(json['data']),
      author: User.fromJson(json['author'] as Map<String, dynamic>),
      id: json['id'] as String,
      type: $enumDecodeNullable(_$MessageTypeEnumMap, json['type']) ??
          MessageType.custom,
      createdAt: json['createdAt'] as int?,
      metadata: json['metadata'] as Map<String, dynamic>?,
      roomId: json['roomId'] as String?,
      status: $enumDecodeNullable(_$StatusEnumMap, json['status']),
    );

Map<String, dynamic> _$CommunityActivityMessageToJson(
        CommunityActivityMessage instance) =>
    <String, dynamic>{
      'author': instance.author.toJson(),
      'createdAt': instance.createdAt,
      'id': instance.id,
      'metadata': instance.metadata,
      'roomId': instance.roomId,
      'status': _$StatusEnumMap[instance.status],
      'type': _$MessageTypeEnumMap[instance.type],
      'data': instance.data.toJson(),
    };

const _$MessageTypeEnumMap = {
  MessageType.custom: 'custom',
  MessageType.file: 'file',
  MessageType.image: 'image',
  MessageType.text: 'text',
  MessageType.unsupported: 'unsupported',
};

const _$StatusEnumMap = {
  Status.delivered: 'delivered',
  Status.error: 'error',
  Status.seen: 'seen',
  Status.sending: 'sending',
  Status.sent: 'sent',
};

**Comment by demchenkoalex** [comment]
Hey @Mayb3Nots this was never the intention. To create a custom message type you extend `Message` (like all other messages, including custom one), not `CustomMessage`. So this will no longer be possible, since it was not intended to work like that. Anyway, if you copy `CustomMessage` code, just replace fields with yours (add `CommunityActivitiesData) and that would be all.

**Comment by Mayb3Nots** [comment]
> 



> 

Ahhh i see now so we should have extended `Message `class instead of CustomMessage gotcha. I think it should be documented somewhere. also I believe @Yogesh-Dubey-Ayesavi was having the same issue so this can be closed now.

**Comment by demchenkoalex** [comment]
This is not supposed to be used directly, hence no documentation :) Obviously adding docs is easy, but I will be encouraging people to fork the library, which I don't want. Eventually, when we will have reactions, replies, audio/video messages, it should cover most of the cases.

**Comment by Yogesh-Dubey-Ayesavi** [comment]
Well i have made my own implementation for this and it works nicely @Mayb3Nots  the way you did is actually more complex then it has to be if your need is simple you should just extend custom message.
