### ISSUE TITLE
Question: Extending Message Types

### ISSUE THREAD

**Issue by LegendAF** [flyerhq/flutter_chat_types#8]
We are evaluating using Flyer (it looks fantastic so far) for a project we are working on. I have one question about Message Types... I see that currently File, Image, and Text are supported. Can the Types be extended easily if we plan to add additional features and use our own backend? If so, is there a suggested way of doing this that will fall in line with future updates to the package?

Thanks for taking the time to answer this :)

**Comment by demchenkoalex** [comment]
Hi @LegendAF, thanks for the feedback! We for sure will be adding the "System" type or something similar, which is usually used in a conversation with support and "Audio", "Video" somewhere down the road. What message types are you thinking of? Maybe we should consider other options.

Regarding the extension, I'm not sure if it can be extended right now, maybe only if we do a type called "Other" with a metadata Map and then in the chat UI if we see the type "Other" we expect a widget which will render this message? This is the first thing that came to my mind, but I'm open to any suggestions that you have to implement/improve what we have right now.

**Comment by Goxiaoy** [comment]
@demchenkoalex 

I do not think current design is extendable and there would be version compatibility issues.
Once a new added message type is released, for the users who are still using olds packages will most likely show blank message screen or even crash due to some behavior like
https://github.com/flyerhq/flutter_chat_types/blob/710708ba5b1aff11f1d4cedc9e25c2ec54cdd924/lib/src/message.dart#L30-L38

There is a factory pattern to make it extendable
https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/3a16247cad4eabc9aaf6eb890c0400c5a191f7ba/lib/src/rong_im_client.dart#L57-L129
And the 'Unsupported' message type should be considered for version compatibility

**Comment by demchenkoalex** [comment]
Hi @Goxiaoy I don't consider myself a dart expert, so if you can help out with a "right way" to do it (even with a breaking change - we will have it soon anyway) that would be cool.

**Comment by demchenkoalex** [comment]
Just another thought - user will not use this package directly, it is bundled with a Chat UI. So when new features are added, the new Chat UI and/or Firebase Core is released, so I don't expect any crashes, since you can still use an old version. And because you are on an old version you don't have an option to create a new message type as well. What is the possible situation where this will be a compatibility issue? Other than removing message types which is not planned.

**Comment by Goxiaoy** [comment]
> Hi @Goxiaoy I don't consider myself a dart expert, so if you can help out with a "right way" to do it (even with a breaking change - we will have it soon anyway) that would be cool.

I am really busy these days for finding tech stacks for my company, and occasionally find this package. I will keep watching this project and see what I can do in the frontend/backend once I have  enough time



> Just another thought - user will not use this package directly, it is bundled with a Chat UI. So when new features are added, the new Chat UI and/or Firebase Core is released, so I don't expect any crashes, since you can still use an old version. And because you are on an old version you don't have an option to create a new message type as well. What is the possible situation where this will be a compatibility issue? Other than removing message types which is not planned.

You can not force evey end user to upgrade their app immediately. Once developers release a new version of app with the new version of Chat UI and/or Firebase Core, end users will face compatibility issue. It better to have some friendly notice like 'Your app does not support this kind of message , please upgrade your app to latest' instead of missing error handling

**Comment by demchenkoalex** [comment]
Oh okay, right. Thanks for bringing this up! We will work on that

**Comment by demchenkoalex** [comment]
Added `custom` and `unsupported` message types. `custom` has `metadata` map, which can be used to store anything and new version of the Chat UI will have `buildCustomMessage` function to build anything. `unsupported` will be used for backwards compatibility. Released in [v2.2.0](https://github.com/flyerhq/flutter_chat_types/releases/tag/v2.2.0).
